
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Next186_SoC(
// CLOCK
	input clk27M, // clk50m,

// HDMI
	output       tmds_clk_n,
	output       tmds_clk_p,
	output [2:0] tmds_d_n,
	output [2:0] tmds_d_p,

// SDRAM (Internal connection, "magic" ports -- Gowin auto-places these
// to the SIP SDRAM on Tang Nano 20K, no .cst entries needed/possible)
	inout  wire [31:0]  IO_sdram_dq,
	output wire [10:0]  O_sdram_addr,
	output wire [1:0]   O_sdram_ba,
	output wire         O_sdram_cs_n,
	output wire         O_sdram_wen_n,
	output wire         O_sdram_ras_n,
	output wire         O_sdram_cas_n,
	output wire         O_sdram_clk,
	output wire         O_sdram_cke,
	output wire [3:0]   O_sdram_dqm,

// SPI
	//output flash_ncs,		// active low
	//output rtc_cs,			// active high
	//input mmc_ncd,			// low when card present
	//input mmc_wp,  		// high on write protect
	output mmc_ncs,		// SD-CARD active low
	output spi_clk,
	input spi_miso,
	output spi_mosi,
	output [1:0] spi_pup,
	
// PS2
	//inout ps2_mouse_dat,
	//inout ps2_mouse_clk,
	inout ps2_kb_dat,
	inout ps2_kb_clk,	

// FPGA Companion SPI (RP2040 / M0S Dock) — identical pinout to NanoMig
// for compatibility with existing RP2040 wiring on Tang Nano 20K
	input  mcu_spi_csn,   // active low, pin 56
	input  mcu_spi_sck,   // pin 54
	input  mcu_spi_mosi,  // pin 41
	output mcu_spi_miso,  // pin 42
	output mcu_spi_irq,   // active low, pin 51

// RS232
	input usart_rx,
	output usart_tx,
	//input usart_rts,
	//output usart_clk,
	
// AUDIO	
	output sigma_l,
	output sigma_r,
	
// IR
	//input ir_data,
	
// BUTTONS - normal 1, 0 when pushed
	//input usart_cts,		// left
	//input freeze_btn,		// middle
	//input reset_btn,		// right
	
	input  [1:0] 	BTN,	// BTN[1]=reset
	//output [5:0]	gpio,
    output [5:0]	LED
	
);

	// GPIO is driven by system.v (output [7:0] GPIO there) ??? must be declared
	// as an 8-bit wire here too, otherwise Verilog treats a bare, undeclared
	// "GPIO" as an implicit 1-bit net and GPIO[1:0] below fails to compile.
	wire [7:0] GPIO;

	// TMDS serial data from the OSER10 serializers, one bit per HDMI lane,
	// fed to the differential output buffers below. Also needs an explicit
	// declaration for the same reason.
	wire [2:0] tmds_d;

	// Normal board status LEDs: PLL lock + GPIO/SPI status.
	// LED[0]: dedicated diagnostic bit -- lights up (and LATCHES, stays lit)
	// the first time the video FIFO is ever caught empty/almost-empty while
	// actively displaying a pixel (system.v: vga_underrun_latched, sourced
	// from led[7], the bit that used to be a hardcoded 0 in the LED
	// concatenation). Off since power-on = FIFO never starved during
	// display -> the visible glitching is coming from somewhere else
	// (fetch addressing/content, not FIFO throughput). Lit = confirms a
	// genuine underrun is really happening and is worth chasing further.
	// LED[0] = Companion SPI activity (lights when FPGA sees SPI bytes from Pico)
	// LED[5:1]: CPU instruction-address heartbeat.
	// (LEDs are active-low on Tang Nano 20K)
	wire spi_activity;


	assign ram_cs = 1'b0; 		//// 
	assign spi_pup = 2'b11;		////
	assign ps2iec_sel = 1'b0;	// ps2 active
	assign flash_ncs = 1'b1;	// flash inactive
	assign rtc_cs = 1'b0;		// rtc inactive
/*
	wire clk50m,clk1m;
	clk50m	clk50m_inst (
		.inclk0 ( clk12m ),	.c0 ( clk50m ),	.locked (  ));
	wire SDR_CLK,wire clk_25;
	dd_buf sdrclk_buf(
		.datain_h(1'b1),.datain_l(1'b0),.outclock(SDR_CLK),.dataout(ram_clk));
*/
	wire clk_ps,pll_lock1,pll_lock2;
	wire pll_lock = pll_lock1 && pll_lock2;
	wire sdram_clk_p;
    wire clk_div4, clk_div3;
    Gowin_rPLL clkgen(
        .clkin(clk27M),
        .reset(por_reset),
        .clkout(clk_ps),	// 64.8MHz
        .clkoutd(clk_div4),	// 16.2MHz (div 4)
        .clkoutd3(clk_div3), // 21.6MHz (div 3)
        .clkoutp(sdram_clk_p),	// phase-shifted clock for O_sdram_clk
        .lock(pll_lock1)
    );
    wire clk50m = clk_div3; // 21.6 MHz CPU clock (+33% over 16.2 MHz)
	wire sdram_clk = clk_ps;	// same clock domain drives CPU and SDRAM, as on the 9K (psram_clk was clk_ps too)


  
`ifndef SIMULATION
  wire clk_p, clk_p5;	// p5:125.875  p:25.175
  Gowin_rPLL2 u_pll (.clkin(clk27M), .clkout(clk_p5), .lock(pll_lock2), .reset(por_reset) );
  Gowin_CLKDIV u_div_5 ( .clkout(clk_p), .hclkin(clk_p5), .resetn(pll_lock2) );
`else
  wire clk_p = clk27M;
  wire clk_p5 = clk27M;
  assign pll_lock2 = 1'b1;
`endif


// Hardware Power-On Reset generator (adapted from snestang for Tang Nano 20K):
// Holds system in reset for ~10ms (262,144 cycles of 27MHz) until both PLLs
// are fully locked and power rails have stabilized. Eliminates power-up races
// and empty blinking cursor hangs.
// Tang Nano 20K: buttons are ACTIVE-HIGH (0 at rest, 1 when pressed)
wire btn_reset = BTN[1]; // S2 on pin 87: 1 when pressed, 0 at rest
wire btn_user  = BTN[0]; // S1 on pin 88: 1 when pressed, 0 at rest

`ifdef SIMULATION
reg [18:0] por_cnt = 19'd50;
`else
reg [18:0] por_cnt = 19'h7ffff;
`endif
reg        por_reset = 1'b1;
always @(posedge clk27M) begin
    if (btn_reset) begin
        por_cnt   <= 19'h7ffff;
        por_reset <= 1'b1;
    end else if (por_cnt != 19'd0) begin
        por_cnt   <= por_cnt - 1'b1;
        por_reset <= 1'b1;
    end else begin
        por_reset <= 1'b0;
    end
end
wire breset = por_reset;
wire resetn = !por_reset;
wire clk_pixel = clk_p;
wire [5:0] rout_sys, gout_sys, bout_sys;
wire hsync_ns, vsync_ns, hblnk_ns;
wire [7:0] led;

// -------------------------------------------------------------------------
// HDMI output: use the raster generated by system.v directly.
// There is intentionally no second/free-running HDMI raster, no debug
// overlay and no colour-bar fallback. The RGB, HSYNC, VSYNC and blanking
// all come from the same pixel-clock domain inside system.v. This keeps
// pixels and timing locked to the VGA/SDRAM pipeline and follows the
// reference Tang-Nano implementation, where VGA timing is converted to
// HDMI after the raster has already been generated.
// -------------------------------------------------------------------------
wire [7:0] hdmi_r = {rout_sys, 2'b00};
wire [7:0] hdmi_g = {gout_sys, 2'b00};
wire [7:0] hdmi_b = {bout_sys, 2'b00};
// Delay DE, HSYNC and VSYNC by 19 pixel clocks to perfectly match the internal
// video pipeline latency of system.v (FIFO read -> latch -> DAC -> output FF).
// Without this delay, DE asserts before the pixel data emerges, causing an
// unwanted black margin on the left and cutting off active pixels on the right.
reg [18:0] de_sft = 19'b0;
reg [18:0] hsync_sft = 19'b0;
reg [18:0] vsync_sft = 19'b0;

always @(posedge clk_pixel) begin
    de_sft    <= {de_sft[17:0], !hblnk_ns};
    hsync_sft <= {hsync_sft[17:0], hsync_ns};
    vsync_sft <= {vsync_sft[17:0], vsync_ns};
end

wire out_hsync = hsync_sft[18];
wire out_vsync = vsync_sft[18];
wire out_de    = de_sft[18];

// Synchronize PLL2 lock into the pixel clock before releasing the HDMI
// encoder/serializer reset. This is an implementation reset synchronizer,
// not a data-path CDC, and it prevents startup races between PLL lock and
// the 25.2 MHz video pipeline.
reg [3:0] hdmi_reset_sync = 4'b0000;
always @(posedge clk_pixel or negedge pll_lock2) begin
    if (!pll_lock2)
        hdmi_reset_sync <= 4'b0000;
    else
        hdmi_reset_sync <= {hdmi_reset_sync[2:0], 1'b1};
end
wire hdmi_resetn = hdmi_reset_sync[3];

// -------------------------------------------------------------------------
// Second reset synchronizer stage, this time in the FAST clk_p5 (126 MHz)
// domain. hdmi_resetn above is only synchronized to clk_pixel (25.2 MHz);
// the OSER10 serializers are clocked by FCLK=clk_p5, so feeding hdmi_resetn
// straight into their asynchronous RESET violates recovery timing on
// deassertion (reset released just inside the clk_p5 switching window).
// This stage re-synchronizes the deassertion edge into clk_p5 so RESET
// only ever comes up aligned to that clock.
// -------------------------------------------------------------------------
reg [1:0] serdes_rst_sync = 2'b11;
always @(posedge clk_p5 or negedge hdmi_resetn) begin
    if (!hdmi_resetn)
        serdes_rst_sync <= 2'b11;
    else
        serdes_rst_sync <= {serdes_rst_sync[0], 1'b0};
end
wire serdes_reset = serdes_rst_sync[1]; // active-high, feeds OSER10 RESET

wire [9:0] tmds_d0, tmds_d1, tmds_d2;
svo_tmds hdmi_enc0 (
    .clk(clk_pixel),  .resetn(hdmi_resetn), .de(out_de),
    .ctrl({out_vsync, out_hsync}), .din(hdmi_b), .dout(tmds_d0)
);
svo_tmds hdmi_enc1 (
    .clk(clk_pixel),  .resetn(hdmi_resetn), .de(out_de),
    .ctrl(2'b00), .din(hdmi_g), .dout(tmds_d1)
);
svo_tmds hdmi_enc2 (
    .clk(clk_pixel),  .resetn(hdmi_resetn), .de(out_de),
    .ctrl(2'b00), .din(hdmi_r), .dout(tmds_d2)
);

`ifndef SIMULATION
OSER10 hdmi_serdes0 (
    .Q(tmds_d[0]), .D0(tmds_d0[0]), .D1(tmds_d0[1]), .D2(tmds_d0[2]), .D3(tmds_d0[3]), .D4(tmds_d0[4]),
    .D5(tmds_d0[5]), .D6(tmds_d0[6]), .D7(tmds_d0[7]), .D8(tmds_d0[8]), .D9(tmds_d0[9]),
    .PCLK(clk_pixel), .FCLK(clk_p5), .RESET(serdes_reset)
);
OSER10 hdmi_serdes1 (
    .Q(tmds_d[1]), .D0(tmds_d1[0]), .D1(tmds_d1[1]), .D2(tmds_d1[2]), .D3(tmds_d1[3]), .D4(tmds_d1[4]),
    .D5(tmds_d1[5]), .D6(tmds_d1[6]), .D7(tmds_d1[7]), .D8(tmds_d1[8]), .D9(tmds_d1[9]),
    .PCLK(clk_pixel), .FCLK(clk_p5), .RESET(serdes_reset)
);
OSER10 hdmi_serdes2 (
    .Q(tmds_d[2]), .D0(tmds_d2[0]), .D1(tmds_d2[1]), .D2(tmds_d2[2]), .D3(tmds_d2[3]), .D4(tmds_d2[4]),
    .D5(tmds_d2[5]), .D6(tmds_d2[6]), .D7(tmds_d2[7]), .D8(tmds_d2[8]), .D9(tmds_d2[9]),
    .PCLK(clk_pixel), .FCLK(clk_p5), .RESET(serdes_reset)
);

ELVDS_OBUF hdmi_buf_clk (.I(clk_pixel), .O(tmds_clk_p), .OB(tmds_clk_n));
ELVDS_OBUF hdmi_buf0     (.I(tmds_d[0]), .O(tmds_d_p[0]), .OB(tmds_d_n[0]));
ELVDS_OBUF hdmi_buf1     (.I(tmds_d[1]), .O(tmds_d_p[1]), .OB(tmds_d_n[1]));
ELVDS_OBUF hdmi_buf2     (.I(tmds_d[2]), .O(tmds_d_p[2]), .OB(tmds_d_n[2]));
`else
assign tmds_d = {tmds_d2[0], tmds_d1[0], tmds_d0[0]};
assign tmds_clk_p = clk_pixel;
assign tmds_clk_n = ~clk_pixel;
assign tmds_d_p = tmds_d;
assign tmds_d_n = ~tmds_d;
`endif

wire [20:0] live_iaddr;
wire [7:0] debug_status_unused;
tri1 ps2_mouse_clk;
tri1 ps2_mouse_dat;

// Companion → 8042 inject wires
wire        inject_kb_stb;
wire [7:0]  inject_kb_data;
wire        inject_mouse_stb;
wire [7:0]  inject_mouse_data;

reg [21:0] kb_act_cnt = 0;
always @(posedge clk50m) begin
	if (inject_kb_stb) kb_act_cnt <= 22'd2_500_000;
	else if (kb_act_cnt != 0) kb_act_cnt <= kb_act_cnt - 1'b1;
end
wire kb_activity = (kb_act_cnt != 0);

reg [21:0] ms_act_cnt = 0;
always @(posedge clk50m) begin
	if (inject_mouse_stb) ms_act_cnt <= 22'd2_500_000;
	else if (ms_act_cnt != 0) ms_act_cnt <= ms_act_cnt - 1'b1;
end
wire ms_activity = (ms_act_cnt != 0);

// LED[0] = SPI traffic from Pico
// LED[1] = USB Keyboard event received
// LED[2] = USB Mouse event received
// LED[5:3] = CPU heartbeat
assign LED = {~live_iaddr[2:0], ~ms_activity, ~kb_activity, ~(spi_activity | led[7])};

	system sys_inst
	(
		//.clk_sdr(clk_ps),
 		//.sdr_CLK_out(SDR_CLK),
		.CLK_50MHZ(clk50m),
		.clk_pixel(clk_pixel),
		.VGA_R(rout_sys),
		.VGA_G(gout_sys),
		.VGA_B(bout_sys),
		.frame_on(),
        .DEBUG_LIVE_IADDR(live_iaddr),
		.DEBUG_STATUS(debug_status_unused),
		.VGA_HSYNC(hsync_ns),
		.VGA_VSYNC(vsync_ns),
		.VGA_hblnk(hblnk_ns),
		.LED(led),
		.BTN_RESET(breset),
		.BTN_NMI(1'b0), // (!freeze_btn),
		.BTN_USER(btn_user),
		.RS232_DCE_RXD(usart_rx),
		.RS232_DCE_TXD(usart_tx),
		.RS232_EXT_RXD(1'b1),
		.RS232_EXT_TXD(),
		 // SDRAM(Internal connection)
		.sdram_clk(sdram_clk),
		.sdram_clk_p(sdram_clk_p),
		.pll_lock(pll_lock),
		.IO_sdram_dq(IO_sdram_dq),
		.O_sdram_addr(O_sdram_addr),
		.O_sdram_ba(O_sdram_ba),
		.O_sdram_cs_n(O_sdram_cs_n),
		.O_sdram_wen_n(O_sdram_wen_n),
		.O_sdram_ras_n(O_sdram_ras_n),
		.O_sdram_cas_n(O_sdram_cas_n),
		.O_sdram_clk(O_sdram_clk),
		.O_sdram_cke(O_sdram_cke),
		.O_sdram_dqm(O_sdram_dqm),

		.SD_n_CS(mmc_ncs),
		.SD_DI(spi_mosi),
		.SD_CK(spi_clk),
		.SD_DO(spi_miso),
		.AUD_L(sigma_l),
		.AUD_R(sigma_r),

	 	.PS2_CLK1(ps2_kb_clk),
 	   //.PS2_CLK1_nOE(ps2_kb_clk_nOE),
		.PS2_DATA1(ps2_kb_dat),
		//.PS2_DATA1_nOE(ps2_kb_data_nOE),

		.PS2_CLK2(ps2_mouse_clk),
		//.PS2_CLK2_nOE(ps2_mouse_clk_nOE),
		.PS2_DATA2(ps2_mouse_dat),
		//.PS2_DATA2_nOE(ps2_mouse_data_nOE),

		.RS232_HOST_RXD(1'b1),
		.RS232_HOST_TXD(),
		.RS232_HOST_RST(),

		.inject_kb_stb(inject_kb_stb),
		.inject_kb_data(inject_kb_data),
		.inject_mouse_stb(inject_mouse_stb),
		.inject_mouse_data(inject_mouse_data),

		.mcu_sdc_strobe   (mcu_sdc_strobe),
		.mcu_start        (mcu_start),
		.mcu_dout         (mcu_dout),
		.mcu_sdc_din      (mcu_sdc_din),
		.sdc_irq_n        (sdc_irq_n),

		.GPIO(GPIO),
		.I2C_SCL(),
		.I2C_SDA()
	);

	// -------------------------------------------------------------------------
	// FPGA Companion interface (SPI slave + HID + SYSCTRL + SDC Storage)
	// Pins match NanoMig / MiSTeryNano so existing RP2040 wiring works.
	// -------------------------------------------------------------------------
	wire        mcu_sys_strobe, mcu_hid_strobe, mcu_osd_strobe, mcu_sdc_strobe;
	wire        mcu_start;
	wire [7:0]  mcu_dout;
	wire [7:0]  mcu_sys_din;
	wire [7:0]  mcu_hid_din;
	wire [7:0]  mcu_osd_din  = 8'h00;
	wire [7:0]  mcu_sdc_din;
	wire        sdc_irq_n;
	wire        sys_irq_n;
	wire        hid_irq_n;
	wire [1:0]  companion_leds;

	// Same clock domain as 8042 (clk_cpu = clk50m) → no CDC for inject_*.
	mcu_spi u_mcu_spi (
		.clk            (clk50m),
		.reset          (por_reset),
		.spi_io_ss      (mcu_spi_csn),
		.spi_io_clk     (mcu_spi_sck),
		.spi_io_din     (mcu_spi_mosi),
		.spi_io_dout    (mcu_spi_miso),
		.mcu_sys_strobe (mcu_sys_strobe),
		.mcu_hid_strobe (mcu_hid_strobe),
		.mcu_osd_strobe (mcu_osd_strobe),
		.mcu_sdc_strobe (mcu_sdc_strobe),
		.mcu_start      (mcu_start),
		.mcu_sys_din    (mcu_sys_din),
		.mcu_hid_din    (mcu_hid_din),
		.mcu_osd_din    (mcu_osd_din),
		.mcu_sdc_din    (mcu_sdc_din),
		.mcu_dout       (mcu_dout),
		.spi_activity   (spi_activity)
	);

	sysctrl_pc u_sysctrl (
		.clk            (clk50m),
		.reset          (por_reset),
		.data_in_strobe (mcu_sys_strobe),
		.data_in_start  (mcu_start),
		.data_in        (mcu_dout),
		.data_out       (mcu_sys_din),
		.buttons        (BTN),
		.hid_irq_n      (hid_irq_n),
		.sdc_irq_n      (sdc_irq_n),
		.int_out_n      (sys_irq_n),
		.leds           (companion_leds)
	);

	hid_pc u_hid_pc (
		.clk             (clk50m),
		.reset           (por_reset),
		.data_in_strobe  (mcu_hid_strobe),
		.data_in_start   (mcu_start),
		.data_in         (mcu_dout),
		.data_out        (mcu_hid_din),
		.inject_kb_stb   (inject_kb_stb),
		.inject_kb_data  (inject_kb_data),
		.inject_mouse_stb(inject_mouse_stb),
		.inject_mouse_data(inject_mouse_data),
		.irq             (hid_irq_n)
	);

	// Combine interrupt sources (active-low open-collector style)
	assign mcu_spi_irq = sys_irq_n & hid_irq_n & sdc_irq_n;
	
endmodule

