// sdram32.v — 32-bit word-oriented variant of nand2mario's SDRAM controller
// for the embedded SDR SDRAM on Tang Nano 20K (GW2AR-18).
//
// Derived from: https://github.com/nand2mario/sdram-tang-nano-20k (Apache-2.0)
// Original file: src/sdram.v, (c) nand2mario, 2022-2023.
//
// CHANGES vs. original (clearly scoped, timing/FSM core is UNTOUCHED):
//   - Original core is byte-addressed: din[7:0]/dout[7:0], with SDRAM_DQM
//     derived internally from addr[1:0] (always writes exactly one byte).
//   - This variant exposes the full 32-bit data path and an explicit 4-bit
//     byte-enable mask (dqm_in), so a caller can do word or partial-word
//     (byte-masked) writes in a single transaction — needed by the Next186
//     CPU bus, which writes 1-4 bytes at a time via `wmask`.
//   - The read/write state machine shape (states, init sequence) is copied
//     from the original; timing-critical parameters were NOT trusted as-is
//     — see below.
//
// REVISION 2 — cross-checked against a second, independently hardware-
// verified source: github.com/nand2mario/nestang, file src/sdram_nes.v +
// src/pllr/gowin_pll_nes.v (same author, later/actively-maintained project,
// explicitly targeting GW2AR-LV18QN88C8/I7 = Tang Nano 20K, confirmed by
// the Gowin-generated IP header in that file). That project uses MORE
// CONSERVATIVE timing than the original standalone sdram-tang-nano-20k demo:
//     T_RP:  1 -> 2   (was too tight: 1 cycle @ 64.8MHz ~= 15.4ns, right at
//                       the SDRAM's tRP minimum with no margin)
//     T_RCD: 1 -> 2   (same reasoning, tRCD minimum)
//     T_RC:  4 -> 6   (tRC minimum needs ~60-63ns; 4 cycles @64.8MHz=~62ns
//                       was borderline; 6 cycles gives real margin)
// This file now uses the sdram_nes.v values (safer, from the more recent of
// the two real hardware-tested designs). CAS/T_WR/T_MRD were already
// identical between both sources (2/2/2) and are unchanged.
//
// Also cross-checked: the PLL feeding SDRAM_CLK. nestang's
// src/pllr/gowin_pll_nes.v (generated by Gowin IDE for GW2AR-18C) uses:
//     FCLKIN=27, IDIV_SEL=4, FBDIV_SEL=11, ODIV_SEL=8  -> CLKOUT = 64.8MHz
//     CLKOUTP: PSDA_SEL="1000", DUTYDA_SEL="1000"      -> 180-deg phase-shifted
//                                                           version of CLKOUT
// and wires CLKOUTP directly to O_sdram_clk with nothing in between
// (nestang_top.sv: "gowin_pll_nes pll_nes(..., .clkoutp(O_sdram_clk));").
// This confirms the architecture used here (a dedicated PLL phase output
// feeding SDRAM_CLK) is the real, tested approach — not a guess — and gives
// a concrete, known-working set of rPLL defparam values to start from
// instead of "regenerate it in the IDE and hope" (see INTEGRATION_PATCH.md).
//
// STILL NOT SIMULATED OR HARDWARE-TESTED AS PART OF *THIS* PROJECT. The
// underlying FSM timing is now backed by two independent real designs
// rather than one; the byte-mask/32-bit-word modification on top of it is
// still original work here and needs your own simulation/bring-up pass.

module sdram32
#(
    parameter         FREQ = 64_800_000,
    parameter         ROW_WIDTH = 11,  // 2K rows
    parameter         COL_WIDTH = 8,   // 256 words per row
    parameter         BANK_WIDTH = 2,  // 4 banks

    parameter [4:0]   CAS  = 5'd2,
    parameter [4:0]   T_WR = 5'd2,
    parameter [4:0]   T_MRD= 5'd2,
    parameter [4:0]   T_RP = 5'd2,
    parameter [4:0]   T_RCD= 5'd2,
    parameter [4:0]   T_RC = 5'd6
    // NOTE: T_RP/T_RCD/T_RC/T_WR/T_MRD/CAS are all [4:0] (5-bit), not [3:0],
    // and `cycle` below is also 5-bit. This was a REAL bug found by
    // simulation (see testbench/): with the old 4-bit width, the CONFIG
    // state's exit condition T_RP+T_RC+T_RC+T_MRD = 2+6+6+2 = 16 silently
    // wrapped to 0 inside a concatenation's self-determined 4-bit context
    // (a classic Verilog width-inference trap: operands inside {a, b+c}
    // are sized to the OPERANDS, not the surrounding assignment target),
    // colliding with the {CONFIG, 4'd0} PRECHARGE case item and making the
    // "done" branch permanently unreachable -> the controller hung in
    // CONFIG forever and ps_calib/init_done never asserted. Confirmed via
    // iverilog simulation (testbench/tb_mem_controller.v), fixed by
    // widening to 5 bits (max useful value 16 fits in 0..31).
)
(
    // SDRAM side ("magic" ports, connect straight to Next186_SoC_20K.v top)
    inout  [31:0]              SDRAM_DQ,
    output reg [ROW_WIDTH-1:0] SDRAM_A,
    output reg [BANK_WIDTH-1:0]SDRAM_BA,
    output                     SDRAM_nCS,
    output reg                 SDRAM_nWE,
    output reg                 SDRAM_nRAS,
    output reg                 SDRAM_nCAS,
    output                     SDRAM_CLK,
    output                     SDRAM_CKE,
    output reg [3:0]           SDRAM_DQM,

    // Logic side interface
    input                      clk,
    input                      clk_sdram,   // phase-shifted clk (PLL clkoutp)
    input                      resetn,
    input                      rd,          // command: read  (1-cycle pulse)
    input                      wr,          // command: write (1-cycle pulse)
    input                      refresh,     // command: auto-refresh (1-cycle pulse)
    input      [22:0]          addr,        // WORD address (32-bit words), buffered at rd/wr pulse
    input      [31:0]          din,         // write data, buffered at wr pulse
    input      [3:0]           dqm_in,      // byte enables for write, active-LOW-per-DQM convention:
                                             //   bit=0 -> that byte IS written, bit=1 -> byte masked out
                                             //   e.g. Next186 wmask[3:0] (active-high "write this byte")
                                             //   must be inverted: dqm_in = ~wmask
    output     [31:0]          dout,        // read data, valid when data_ready pulses, held until next read
    output reg                 data_ready,  // 1-cycle pulse, 4 cycles after rd
    output reg                 busy         // 0: ready for next command
);

reg dq_oen;
reg [31:0] dq_out;
assign SDRAM_DQ = dq_oen ? 32'bz : dq_out;
wire [31:0] dq_in = SDRAM_DQ;

reg [31:0] dout_buf;
assign dout = dout_buf;
// On Tang Nano 20K, the SDRAM is in-package (0 routing delay).
// A 180-degree phase shift (clk_sdram) at 64.8MHz puts the sampling edge
// too close to the data-valid window. Using 0-degree (clk) puts the sampling
// edge exactly in the middle of the valid window (10ns setup, 5ns hold).
assign SDRAM_CLK = clk_sdram;
assign SDRAM_CKE = 1'b1;
assign SDRAM_nCS  = 1'b0;

reg [2:0] state;
localparam INIT=3'd0, CONFIG=3'd1, IDLE=3'd2, READ=3'd3, WRITE=3'd4, REFRESH=3'd5;

localparam CMD_SetModeReg=3'b000, CMD_AutoRefresh=3'b001, CMD_PreCharge=3'b010,
           CMD_BankActivate=3'b011, CMD_Write=3'b100, CMD_Read=3'b101, CMD_NOP=3'b111;

localparam [2:0] BURST_LEN = 3'b0;
localparam BURST_MODE = 1'b0;
localparam [10:0] MODE_REG = {4'b0, CAS[2:0], BURST_MODE, BURST_LEN};

reg cfg_now;
reg [4:0] cycle;                    // widened 4->5 bits, see NOTE above
reg [31:0] din_buf;
reg [3:0]  dqm_buf;
reg [22:0] addr_buf;

always @(posedge clk) begin
    cycle <= cycle == 5'd31 ? 5'd31 : cycle + 5'd1;
    {SDRAM_nRAS, SDRAM_nCAS, SDRAM_nWE} <= CMD_NOP;
    casex ({state, cycle})
        {INIT, 5'bxxxxx} : if (cfg_now) begin state <= CONFIG; cycle <= 0; end

        {CONFIG, 5'd0} : begin
            {SDRAM_nRAS, SDRAM_nCAS, SDRAM_nWE} <= CMD_PreCharge;
            SDRAM_A[10] <= 1'b1;
        end
        {CONFIG, T_RP} : {SDRAM_nRAS, SDRAM_nCAS, SDRAM_nWE} <= CMD_AutoRefresh;
        {CONFIG, T_RP+T_RC} : {SDRAM_nRAS, SDRAM_nCAS, SDRAM_nWE} <= CMD_AutoRefresh;
        {CONFIG, T_RP+T_RC+T_RC} : begin
            {SDRAM_nRAS, SDRAM_nCAS, SDRAM_nWE} <= CMD_SetModeReg;
            SDRAM_A[10:0] <= MODE_REG;
        end
        {CONFIG, T_RP+T_RC+T_RC+T_MRD} : begin
            state <= IDLE; busy <= 1'b0;
        end

        {IDLE, 5'bxxxxx}: if (rd | wr) begin
            {SDRAM_nRAS, SDRAM_nCAS, SDRAM_nWE} <= CMD_BankActivate;
            SDRAM_BA <= addr[ROW_WIDTH+COL_WIDTH+BANK_WIDTH-1 : ROW_WIDTH+COL_WIDTH];
            SDRAM_A  <= addr[ROW_WIDTH+COL_WIDTH-1:COL_WIDTH];
            state <= rd ? READ : WRITE;
            addr_buf <= addr;
            if (wr) begin din_buf <= din; dqm_buf <= dqm_in; end
            else SDRAM_DQM <= 4'b0000;
            cycle <= 5'd1;
            busy <= 1'b1;
        end else if (refresh) begin
            {SDRAM_nRAS, SDRAM_nCAS, SDRAM_nWE} <= CMD_AutoRefresh;
            state <= REFRESH; cycle <= 5'd1; busy <= 1'b1;
        end

        {READ, T_RCD}: begin
            {SDRAM_nRAS, SDRAM_nCAS, SDRAM_nWE} <= CMD_Read;
            SDRAM_A[10] <= 1'b1;
            SDRAM_A[9:0] <= {1'b0, addr_buf[COL_WIDTH-1:0]};
            SDRAM_DQM <= 4'b0;
        end
        // The Tang Nano 20K reference controller exposes READ data one
        // controller clock after the CAS-latency point. The SDRAM clock
        // is phase shifted by 180 degrees, so sampling DQ exactly on the
        // data_ready edge can land on the edge where the memory changes DQ.
        // Capture first, then advertise the stable registered word.
        {READ, T_RCD+CAS+5'd1}: begin
            dout_buf <= dq_in;
            data_ready <= 1'b1;
        end
        {READ, T_RCD+CAS+5'd2}: begin
            data_ready <= 1'b0;
            busy <= 0;
            state <= IDLE;
        end

        {WRITE, T_RCD}: begin
            {SDRAM_nRAS, SDRAM_nCAS, SDRAM_nWE} <= CMD_Write;
            SDRAM_A[10] <= 1'b1;
            SDRAM_A[9:0] <= {1'b0, addr_buf[COL_WIDTH-1:0]};
            SDRAM_DQM <= dqm_buf;      // <-- externally supplied mask (was addr-derived in original)
            dq_out <= din_buf;         // <-- full 32-bit word (was 8-bit replicated in original)
            dq_oen <= 1'b0;
        end
        {WRITE, T_RCD+5'd1}: begin dq_oen <= 1'b1; SDRAM_DQM <= 4'b0000; end
        {WRITE, T_RCD+T_WR+T_RP}: begin busy <= 0; state <= IDLE; SDRAM_DQM <= 4'b0000; end

        {REFRESH, T_RC}: begin state <= IDLE; busy <= 0; SDRAM_DQM <= 4'b0000; end
    endcase

    if (~resetn) begin
        busy <= 1'b1; dq_oen <= 1'b1; SDRAM_DQM <= 4'b0; state <= INIT;
        data_ready <= 1'b0;   // BUG FOUND IN SIMULATION: this was never reset,
                               // so it stayed X until the first real READ ever
                               // completed. An X on data_ready fed straight into
                               // the arbiter's "if (sdr_data_ready) ... else if
                               // (~sdr_busy) ..." branch in mem_controller_20k.v,
                               // and (empirically, in iverilog) did not reliably
                               // take the documented "X is not true" path in this
                               // context, causing the arbiter to fall through and
                               // exit ARB_BUSY after a single cycle instead of
                               // waiting for the real write/refresh to finish.
                               // Explicitly resetting this reg removes the X
                               // hazard at the source rather than relying on
                               // if()-with-X semantics anywhere downstream.
    end
end

reg [14:0] rst_cnt;
reg rst_done, rst_done_p1;
always @(posedge clk) begin
    rst_done_p1 <= rst_done;
    cfg_now     <= rst_done & ~rst_done_p1;
    if (rst_cnt != FREQ / 1000 * 200 / 1000) rst_cnt <= rst_cnt + 15'd1;
    else                                     rst_done <= 1'b1;
    if (~resetn) begin rst_cnt <= 15'd0; rst_done <= 1'b0; end
end

endmodule
